---
galaxy_info:
  author: Ruben Bresler
  description: Deploy Traefik as a Docker or Docker Swarm proxy service
  license: MIT
  min_ansible_version: "2.14"
  galaxy_tags:
    - docker
    - traefik
    - swarm

dependencies: []
